googledrive_root_id <- "1rGCmpaRxNyNLXoBuqgEojcDeI2f7G4uE"
release_spreadsheet_name <- "releases"
local_release_spreadsheet_path = "data/releases.csv"
release_name_prefix = "release_"
local_release_dir = "data/releases"
blast_database_dir = "data/blast_databases"