
## Google Drive folder structure

* **OomcyeteDB database**
  * **database_releases**: A folder containing the spreadsheet files for each release. Once a file is added here it should not be edited.
  * **rps10_database.ods**: A file with the current working version of the oomcyete database. 
  * **releases.ods**: A file with information on the releases of the oomycete database. Adding a line to this file causes an update.
  * **maintenance_guide.odt**: A guide to updating and maintaining the database.

## Proposed format

The database is composed of two spreadsheet files: 

* **rps10_database.ods**: A spreadsheet file named with two sheets: 
  1. **sequence_data**: A table with one row per sequence and associated information, including a taxonomic ID (e.g., ncbi taxid)
    * *name*: The name of the organism as originally described when entered in the database, including the genus, species, and any sub-species level information.
    * *genbank_id*: The GenBank accession number for the sequence. This can be left blank for sequences without an accession.
    * *taxon_id*: The taxon ID for the sequence. For sequences with a GenBank accession, this should be the NCBI taxon ID associated with the accession. For sequences without a GenBank accession, a OomyceteDB-specific taxon identifier starting with "oodb_tax_" is required and there must be an entry in the "taxon_data" sheet corresponding to this ID.  This can be left blank for sequences with a GenBank accession and it will be filled in automatically when the validation script is run.
    * *public*: A column with TRUE/FALSE, determining whether the sequence will appear in the new releases.
    * *auto_update*: A column with TRUE/FALSE, determining whether the validation script can modify data in this row (e.g. add/update NCBI taxon ID for entries with a GenBank accession)
    * *source*: The source of the sequence and taxonomic identification.
    * *sequence*: The sequence, in capital letters representing nucleotides and valid IUPAC.
    * *notes*: Any miscellaneous notes regarding the sequence.
  2. **taxon_data**: A table with one row per unique taxonomic ID and a full classification
    * *taxon_id*: A unique taxon ID, either an NCBI taxon id or a OomyceteDB-specific taxon identifier starting with "oodb_tax_".
    * *auto_update*: A column with TRUE/FALSE, determining whether the validation script should update the classification with the current NCBI taxonomy information.
    * *classification*: The full NCBI taxonomic classification, with ranks separated by ";". For OomyceteDB-specific taxon IDs, this should be added manually.
    * *notes*: Any notes regarding the taxonomic classification.
* **releases.ods**: A table with one row per release
  * *release_number*: Unique release number starting from 1 and incrementing.
  * *release_date*: The date of the release in YYYY-MM-DD format
  * *source_file*: The name of the spreadsheet file in the "database_releases" folder corresponding to the release
  * *public*: A column with TRUE/FALSE, determining whether the release should be made public.
  * *release_notes*: Any miscellaneous notes regard the release. Should include what had changed since the last release.

## Update procedure

1. Between releases, the **rps10_database.ods** file is manually edited. 
2. Before a release, a validation script is run to check that the database is in the correct format and that fills in missing data and updates taxonomic data that might have changed on GenBank.
3. A line is added to the release.ods file
4. During the next night, the release is automatically added to the server using a cron job.
